config/routes.rb
Rails.application.routes.draw do
  get 'products/home'
 
  get 'products/login'

  get 'products/homexls'

  get 'products/hxls'

  get 'products/dd'

  get 'products/result1'
  
  post 'products/result1'

  get 'products/login_process'

  get 'products/new_account'

  get 'products/new_account_process'

  get 'products/browser'

  get 'products/help_browser'

  get 'products/browser_process'

  get 'products/result'

  get 'products/result_process'

  get 'products/aboutus'

  get 'products/description'

  get 'products/details'

  get 'products/logout'
  get 'products/search_edit'

  post 'products/result'

  put 'products/result_process'

  patch 'products/result_process'

  post  'products/result_process'

  get 'products/manu_edit2'

  post 'products/login'

  post 'products/login_process'
 
  post 'products/browser'

  post 'products/browser_process'

  post 'products/new_account_process'

  post 'products/description'

  post 'products/details'

  post 'products/aboutus'

  post 'products/logout'
  
  post 'products/home'

  post 'products/homexls'
 
  post 'products/hxls'

  post 'products/dd'

  get 'products/show'
  get 'products/manu_cate'
  get 'products/manu1'
  get 'products/manu1_edit'
  get 'products/manu_desc'
  get 'products/compare'
  get 'products/manu_index_compare'
  get 'products/manu_compare'
post 'products/manu_index_compare'
  post 'products/manu_compare'
  get 'products/compare_process'

  post 'products/compare'

  post 'products/compare_process'
   get 'products/manu'
resources :products do
get 'dest2'

  
  get 'manu_index'
  

 end

  

   root 'products#home'

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

$nn=[]

require 'will_paginate/array'

 def home

     @product=Product.where(:parent_id=>nil)
   
 end

 def browser
 
     @product=Product.new
  
     respond_to do |format|
    
     format.html
    
     format.csv { send_data @product.to_csv }
    
     format.xls
  
     end
end

def homexls
    
    @aa=[]
  
    @aa << Product.where(:parent_id=>params[:product][:id]).pluck(:id)
  
    @aa.map do |o|
  
    o.map do |i|

    if Product.where(:parent_id=>i).present?
 
    @aa << Product.where(:parent_id=>i).pluck(:id)

    else

    $b=Mfrindex.where(:p_id=>i).only(:i_id).uniq

    end

    end

    end

    render :action=>"dd"
end

def hxls
    
    rr=Sku.where(:id=>params[:sku][:id])

    rrr=rr.mn.pluck(:value)[0]

    $b= Mfrindex.where(m_name:rrr).only(:i_id).uniq

    render :action=>"dd"

end

def dd

    @product=Product.all

end


 def login
 
     @admi=Admin.new

 end

 def login_process

     params.require(:email)
    
     params.require(:password)
     
     @admi=Admin.where params.permit(:email,:password)

     if not @admi.blank?

        session[:admi_id]=@admi.first.id

        flash[:notice] = "Successfully login..."

        redirect_to :action=>"browser"

      else

         flash[:notice] = "Invalid email/password combination" if params[:email] || params[:password]

         redirect_to :action => "login"
 
      end
 
 end 

 def logout
 
      session[:admi_id]=nil

      flash[:notice] = "Successfully logout..."

      redirect_to :action => "home"

 end

 def new_account

     @admi=Admin.new

 end

 def new_account_process
 
     @admi=Admin.new(admi_params)
    
     if @admi.save
    
        UserMailer.sign_up(@admi).deliver
    
        flash[:notice] = "Successfully create a new account..."

        redirect_to :action=>"browser"
  
     else
    
       redirect_to :action=>"new_account"
    
     end
 end


 def help_browser
 
     send_file Rails.root.join('public/files', 'sample.xls'), :type=>"application/xls", :x_sendfile=>true

 end
 
 def browser_process

     file=params[:product][:file1]

     filename=params[:product][:file1].original_filename

     @product=Product.browser(file)
    
     unless @product.blank?
    
     redirect_to :action=> "browser"
 
     flash[:notice] = "Your file has been successfully imported in a database..."
   
  else

     flash[:notice] = "Invalid file headers or file format"
     
     redirect_to :action=> "browser"
    
  end
 
 end

 
def search_edit
  
    $t=nil
   
    @taxo7=[]
   
    @sku=params[:format]

    @sku2=Sku.where(:i_id=>@sku)
         
    @img=(@sku2.imma).pluck(:value)[0]

    @ml=(@sku2.ml).pluck(:value)[0]
   
    @sku1=@sku2.att
 
    @sku3=@sku2.glo

    @sku4=@sku2.ex
 
    @sku5=@sku2.des

    @sku6=@sku2.ht || @sku2.pd

    @sku7="#{@sku2.fb}".split("|")
    
    @check=@sku2.pluck(:i_id)[0]

    @rel1=Sku.where(:i_id=>params[:format]).pluck(:p_id)[0]

    @cat=Sku.where(:p_id=>@rel1).distinct(:i_id)
   
    @ta=Sku.where(:i_id=>params[:format]).pluck(:p_id)[0]

begin

    s=nil

    @tax=Product.where(:id=>@ta)

    tax1=Product.where(:id=>@ta).pluck(:parent_id)[0]
     
    @taxo7<<@tax

    @ta=@tax.pluck(:parent_id)[0]

end until tax1==s

    $cath1=[]

    @taxo7.select{|i| $cath1<<i.where(:parent_id=>nil).pluck(:cat_name)[0]}
end

def search_edit
  
    $t=nil
   
    @taxo7=[]
   
    @sku=params[:format]

    @sku2=Sku.where(:i_id=>@sku)
         
    @img=(@sku2.imma).pluck(:value)[0]

    @ml=(@sku2.ml).pluck(:value)[0]
   
    @sku1=@sku2.att
 
    @sku3=@sku2.glo

    @sku4=@sku2.ex
 
    @sku5=@sku2.des

    @sku6=@sku2.ht || @sku2.pd

    @sku7="#{@sku2.where(:name=>'Feature Bullet').pluck(:value)[0]}".split("|")
    
    @check=@sku2.pluck(:i_id)[0]

    @rel1=Sku.where(:i_id=>params[:format]).pluck(:p_id)[0]

    @cat=Sku.where(:p_id=>@rel1).distinct(:i_id)
   
    @ta=Sku.where(:i_id=>params[:format]).pluck(:p_id)[0]

begin

    s=nil

    @tax=Product.where(:id=>@ta)

    tax1=Product.where(:id=>@ta).pluck(:parent_id)[0]
     
    @taxo7<<@tax

    @ta=@tax.pluck(:parent_id)[0]

end until tax1==s

    $cath1=[]

    @taxo7.select{|i| $cath1<<i.where(:parent_id=>nil).pluck(:cat_name)[0]}
end

def compare

    @cc=params[:is]

    @dd1,@dd2,@dd3=[],[],[]
 
    @cc.each do |i|

    @dd1<<(Sku.where(:i_id=>i).att).pluck(:name)

    @dd2<<(Sku.where(:i_id=>i).glo).pluck(:name)

    @dd3<<(Sku.where(:i_id=>i).imma).pluck(:name)
        
    end

    @n=[@dd2+@dd3+["IMAGE Link-1"]+@dd1].flatten.uniq

end

def manu_index_compare
 
    @cc=params[:is]

    @dd1,@dd2,@dd3=[],[],[]
 
    @cc.each do |i|

    @dd1<<(Sku.where(:i_id=>i).att).pluck(:name)

    @dd2<<(Sku.where(:i_id=>i).glo).pluck(:name)

    @dd3<<(Sku.where(:i_id=>i).imma).pluck(:name)
        
    end

    @n=[@dd2+@dd3+["IMAGE Link-1"]+@dd1].flatten.uniq

end

def manu_compare
  
    @cc=params[:is]

    @dd1,@dd2,@dd3=[],[],[]
 
    @cc.each do |i|

      @dd1<<(Sku.where(:i_id=>i).att).pluck(:name)
     
      @dd2<<(Sku.where(:i_id=>i).glo).pluck(:name)
     
      @dd3<<(Sku.where(:i_id=>i).imma).pluck(:name)
        
    end

    @n=[@dd2+@dd3+["IMAGE Link-1"]+@dd1].flatten.uniq
end

def manu_cate

    @productm=Product.where(parent_id:nil).order("cat_name ASC")
  
end

def manu_index



 $root=Product.where(:id=>params[:product_id]).pluck(:cat_name)[0]
$root1=Product.where(:id=>params[:product_id])
 mfr1=[]
 @@mfr2=[]
 mfr=Mfrindex.all.to_a#select(:taxonomy)
 mfr.each do |i| 
  
  @c=i.taxonomy.split('>')[0]
  if $root==@c
    @@mfr2<<i.p_id

  mfr1<<i.m_name
  
 end
 
 end
@mfr=mfr1.uniq

end
def result1

   @nn1=[]
 
   $param2=params[:search]
 
   @param=(params[:search])
 
   $skuu=Sku.where(:value=>/.*#{@param}*./i)
 
   $skuu.each do |i|
  
     @nn1 << i.i_id
 
   end

   n11= @nn1&@nn1

   if $nn.blank?

      $nn << n11

   else
  
      $nn.clear
  
      $nn << n11
   
   end

      redirect_to :action=>"result"
end

def result

   @kk1=$nn
 
   @kk2=@kk1.flatten

   $ssk=@kk2.paginate(:page => params[:page], :per_page => 10)
 
end




def manu

    $tax=[]

    @taxo1=[]

    @taxo2=[]

    $taxo12=[]

    if Sku.mn.where(:value=>params[:format]).any? 

      $h=Sku.mn.where(:value=>params[:format]).pluck(:value)[0]
    
      @sk1=Sku.where(:value=>params[:format]).distinct(:p_id)
    
      @sk2=@sk1.map{|i| Product.where(:id=>i)}
    
      @sk1.each do|i|
        
        @ta=i
    
        loop do
          
          @tax=Product.where(:id=>@ta)

          @ta=@tax.pluck(:parent_id)[0]
    
          $tax<<@tax.pluck(:id)[0]
    
          break if @ta==nil
    
        end 
    
      end
      
      @taxo1=$tax.uniq.map{|i| Product.where(:id=>i)}.flatten.sort
      
      @tt=@taxo1.select{|i| i.parent_id==nil}
      
      $tax1=@taxo1
      
    else 
  
      unless Product.where(:parent_id=>params[:format]).present?

      if params[:is].class == Array

          @pkk2=params[:is].uniq.collect{|i| Sku.where(:i_id=>i).where(:value=>$h).pluck(:i_id)}.uniq

          @ii=params[:format]

          @pkk3=@pkk2.paginate(:page => params[:page], :per_page => 10)

      else
 
          @ii=params[:format]
 
          @i=params[:format]
 
          @pkk1=Sku.where(:p_id=>@i).where(:value=>$h)
 
          @pkk2=@pkk1.distinct(:i_id)
 
          @pkk3=@pkk2.paginate(:page => params[:page], :per_page => 10)
 
     end
 
    else
       
          @ii=params[:format]
 
          @nn=Product.where(:id=>params[:format].to_s).pluck(:cat_name)[0]

          $taxo=$tax1
 
          $taxo.each do|i|

            if i.parent_id==params[:format].to_i
 
                @taxo1<<i
 
            end

          end 
  
  end
    
          $taxo=@taxo1
      
        begin
    
          s=nil
     
          @tax1=Product.where(:id=>@ii)

          tax1=Product.where(:id=>@ii).pluck(:parent_id)[0]
     
          $taxo12<<@tax1

         @ii=@tax1.pluck(:parent_id)[0]

        end until tax1==s

  end 
  
end

def manu1

  $taxo=[]

a="#{params[:format]}".split("/")

if a.count==2
$manufacture=a[1]

@par=a[0]
else
  @par=a[0]
end
@c=[]
 @par1=Mfrindex.where(:m_name=>$manufacture)
 @par1.each{|i|  @c<<i.taxonomy.split('>')}
   
unless Product.where(:parent_id=>@par).present?
  
   if Sku.where(:p_id => @par).where(:value => $manufacture).present?
   if params[:is].is_a? Array
@product1=params[:is].uniq
      @ta=@par

         
         @product3=@product1.paginate(:page => params[:page], :per_page => 10)

else
      @product1=Sku.where(:p_id=>@par).distinct(:i_id)
      @ta=@par

         
         @product3=@product1.paginate(:page => params[:page], :per_page => 10)

end
    end

 else 

  @r=Product.where(:parent_id=>@par).pluck(:cat_name)
@c.each do |i|  
  @kk=i
  @r.each do |j|
  

    if @kk.include?(j)

       @product1=Product.where(:parent_id=>@par).where(:cat_name=>"#{j}")

       @ta=@product1.map{|i| i.parent_id}[0]
       
    end

   end
  end


end
begin
    s=nil
     @tax=Product.where(:id=>@ta)

     tax1=Product.where(:id=>@ta).pluck(:parent_id)[0]
     
 $taxo<<@tax

 @ta=@tax.pluck(:parent_id)[0]

end until tax1==s

 end

def manu_desc
@sh=Sku.where(:p_id=>params[:id])
@sh1=@sh.mn



end



 def dest2
    sku=params[:product_id]
    @sku1=Sku.where(:i_id=>sku)
   
 end

  
 def aboutus
 @product=Product.new
 end
 def set_page
      @product = Product.find(params[:id])

    end

 private

 def product_params

   params.require(:product).permit!

 end

 def admi_params
  params.require(:email)
     params.require(:password)
     params.require(:re_enterpassword)
    params.permit(:email,:password,:re_enterpassword)
 end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/compare.html.erb
<!DOCTYPE html>

<html lang="en">

 <head> 
  
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  
 </head>

 <div class="body-wrap">
 
   <div class="body-container">
 
     <div class="body-header">
 
       <%=link_to $cath.last, product_path(Product.where(:cat_name=>$cath.last).pluck(:id)[0]),:style=>"color:white;"%>
  
      </div>
  
      <div class="body-content">
   
        <div class="container">

          <div class="row">

            <div class="col-md-12">

             <ol class="breadcrumb">

                <% @taxo=$taxo.reverse%>

                   <% @taxo.each do |i|%>

                      <li><%=link_to i.pluck(:cat_name)[0], product_path(i.pluck(:id)[0])%></li><%break if @taxo.last==i%> 
                      
                      <i class="fa fa-angle-double-right" style="font-size: 16px; color:rgb(0, 102, 255);"></i> 
                
                    <%end%>

              </ol>

            </div>
 
          </div>
      
          <br>

          <div class="product-compare">

            <table class="table">

              <thead>

                <i class="fa fa-dot-circle-o" style="font-size: 15px; color: rgb(0, 102, 255);"></i>&nbsp;Indicates product differences. <br>
         
                <br>

                <% @n.each do|j|%>

                  <%next if j=="Global Description"%>

                  <%unless j=="IMAGE Link-1"%>

                    <%@j=j%><%@ss=[]%> 
  
                      <%@cc.each do |i|%>
              
                        <%@i=i%> 
                        
                        <%@pf = Sku.where(:i_id=>@i).where(:name=>@j).pluck(:value,:unit).uniq.join%>
       
                        <%@ss<<@pf%>

                      <%end%>

                      <tr>

                        <%unless ["Manufacturer Name","Manufacturer Part Number","Product Name"].include?(j)%>

                        <%unless @ss.uniq.count==1 %>
 
                          <td><i class="fa fa-dot-circle-o" style="color: rgb(0, 102, 255);"></i>&nbsp;

                           <strong><%=@j%></strong>

                          </td>

                        <%else%>

                          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong><%=@j%></strong></td><%end%>

                  <%else%>

                          <td></td>

                  <%end%>

             <%@ss.each do |i|%>
  
                <%if @j=="Manufacturer Part Number"%>

                  <%if @ss.count(i) == 1%>

                        <%@o=Sku.where(:name=>"Manufacturer Part Number").where(:value=>i).pluck(:i_id)[0]%>
 
                    <td><%= link_to i, edit_product_path(@o)%></td> 

                  <%end%>
                
                <%else%>

                  <%if @ss.count(i) == 1%>
 
                    <td style="color: rgb(0, 102, 255);"><%=i%></td> 

                  <%else%>
 
                    <td><%=i%></td>
 
                  <%end%>

               <%end%>

             <%end%>
 
             </thead>
     
            </tr>
              
 <%else%>
  
  <tr class="odd">

    <td><%@j=j%></td>
              
    <%@cc.each do |i|%>
              
       <%@i=i%> 
                       
       <td align="left"><%@p1 = Sku.where(:i_id=>@i).where(:name=>@j).pluck(:value)[0]%>
                            
          <%if @p1.blank?%>

              <img src="/assets/not.jpeg" alt="Image not available">

          <%else%>

              <%=image_tag @p1%>

          <%end%>

        </td>

    <%end%>

  </tr>

 <%end%>
            
 <%end%></td></tr> 

 

 </table>
 </div>

 </div>
 </div>
 </div>
 </div>

</html>

app/views/products/description.html.erb
...........WELCOME TO BIG BOOK.........

app/views/products/details.html.erb
........WELCOME TO BIG BOOK......

app/views/products/manu_cate.html.erb
<html>

<head>

<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  
<style>

a:hover{ color:white;}

</style>

</head>

<body>

  <div class="body-wrap">
            	
  <div class="body-container">
  
  <div class="body-header">Manufatures Index</div>

  <div class="body-content">
  
  <div class="container">
  
  	<div class="row">
  
  		<div class="col-md-12">
  
  			<span class="sub-title">Please choose a product category to view the manufacturers in that category. </span>
  
	  	</div>
  
	  </div>
<%@count=Mfrindex.pluck(:m_name,:taxonomy).map{|p| [p[0],p[1].split('>')[0]]}%>


<div class="row">

	<% @productm.map do |i|%> 

		<div class="col-md-6">

			<div class="manufacture-index hvr-sweep-to-right">	

     <%@count1=@count.uniq.select{|p| p[1]==i.cat_name}.count%>
            
              <%=link_to i.cat_name+"  (#{@count1})", product_manu_index_path(i)%>

            </div>

		    <div class="clearfix"></div>
                
    	</div>

    <%end%>                          

</div>
 
</div>
                            
</div>

</div>

</div>

</body>

</html>

app/views/products/manu_edit2.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
  <head>


  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<style>

  a:hover{ 
    color:#3c3c3!important;
  }


  .nav-tabs > li.active > a:hover {
    color: white!important;
    cursor: default;
    background-color: #06ADC3 !important;
    border: 1px solid #ddd;
    border-bottom-color: transparent;
}

.nav-tabs > li.active > a, .nav-tabs > li.active > a:focus, .nav-tabs > li.active > a:hover {
    color: white!important;
    cursor: default;
    background-color: #06adc3;
    border: 1px solid #ddd;
    border-bottom-color: transparent;
}

</style>

<style>


.transition {
    -webkit-transform: scale(1.6); 
    -moz-transform: scale(1.6);
    -o-transform: scale(1.6);
    transform: scale(1.6);
}
#content {
  -webkit-transition: all .4s ease-in-out;
  -moz-transition: all .4s ease-in-out;
  -o-transition: all .4s ease-in-out;
  -ms-transition: all .4s ease-in-out;
}

#content {
    width:220px;
    margin:30px;
}

</style>

</head>

<div class="body-wrap">

<div class="body-container">

    <div class="body-header">

    <%=link_to $cath.last, product_path(Product.where(:cat_name=>$cath.last).pluck(:id)[0]), {:style=>"color:white;"}%></h5>
  
     </div>

<div class="body-content">

<div class="container">

<div class="row">
          
            <%@taxo4=$taxo12.reverse%>
          
              <div class="col-md-12">
           
                <ol class="breadcrumb">
            
                    <%@taxo4.map do |i|%>
            
                    <li class="active"><%=link_to i.pluck(:cat_name)[0],  products_manu_path(i.pluck(:id)[0])%></li>
            
                    <%break if @taxo4.last==i%> 

                    <i class="fa fa-angle-double-right" style="font-size: 16px; color: rgb(185, 31, 31);"></i> 
            
                    <%end%>
            
                </ol>
            
              </div>
              
          </div>

     <div class="clearfix"></div>

          <div class="container">

            <div style="background-color: rgb(36, 45, 53);" class="mm">
     
           <ul class="nav nav-tabs">
    
             <li class="active"><a href="#OverView">OverView</a></li>
       
             <li><a href="#menu1">Specifications</a></li>
       
             <li><a href="#menu2">Media</a></li>
          
           </ul>

          </div>


          <div class="tab-content">
               <div id="OverView" class="tab-pane fade in active">
                <p>
                   <div class="pname"><b>
                     <%=@sku3.where(:name=>"Product Name").pluck(:value)[0]%></b>
                   </div>
               <div class="table-responsive ">
                     <table class="table">
                     <tbody>
                     <tr>
                     <td>
                     <%@sku3.map do |i|%>
                     <%next if i.name=="Brand" or i.name=="Product Name"%>
                     <%=i.value%>&nbsp;&nbsp;
                     <%end%>
                     </td>
                     </tr>
                     </tbody>
                     </table>
                </div>
               <div class="table-responsive">                    
 
    

           

               <%@sku4.map do |i|%>

                 <%next if i.name=="Brand" or i.name=="Product Name"%>
         
                 <%=i.value%>&nbsp;&nbsp;
        
               <%end%>

            
        

           <%if @img.blank?%>




           <img src="/assets/not.jpeg" alt="Image not available">



           <%else%>

          

           <%=image_tag @img,:id=>"content",:style=>"margin-left:25%;"%>

            

           <%end%>
           
          


           <%if @ml.blank?%>

           <img src="/assets/lo-not.jpeg" alt="Logo not available" style="margin-left:25%">

            <%else%>

           <%=image_tag @ml,:style=>"margin-left:25%;" %>

           <%end%>


            



          
        </div>

                <div style="Times New Roman&quot;;" class="table-responsive"> 
                 <table class="table">
                 <tbody>
                     <%@sku5.map do |i|%>
                      <%@ss=i.value.gsub(/~/,'|').split('|')%>
                          <tr>
                               <td>
                           <%@ss.map do|l|%>
                           <div align="left"><%=l%></div>
                              <%end%>
                               </td>
                                </tr>
                             <%end%>
                              </tbody>
                           </table>
                   <table class="table" >
                     <tbody>
                       <tr>
                   <h5 style="color: rgb(0, 0, 0); font-size: large;">Related Products</h5>
                  </tr>
                   <tr style="color: rgb(255, 253, 253); background-color: rgb(6, 173, 195);">
                    <th>
                      <b><center>Item ID</center></b>
                       </th>
                       <th>
                     <b><center>Product Name</center></b>
                      </th>
                    <th>
                     <b><center>Description</center></b>
                   </th>
                     </tr>
                  <%@cat.map do |i|%>
                   <%next if i==@check%>
                   <%@all=Sku.where(i_id:i)%>
                    <tr>
                        <td>
                  <a><%=link_to @all.pluck(:i_id)[0],edit_product_path(@all.pluck(:i_id)[0])%></a>
                   </td>
                     <td>
               <%=@all.where(name:"Product Name").pluck(:value)[0]%>
                     </td>
                    <td>
                    <%=@all.where(name:"Global Description").pluck(:value)[0]%>
                      </td>
                    </tr>
                     <%end%>
                  <tbody>
                 </table>
              </div>
            </p>
             </div>


    <div id="menu1" class="tab-pane fade">
<p>
    <div class="pname">
      <b><%=@sku3.where(:name=>"Product Name").pluck(:value)[0]%></b>
    </div>
    <div style="Times New Roman&quot;;" class="table- responsive ">                
     <table class="table">
       <tbody>
          <tr>
            <td>
              <%@sku3.map do |i|%>
                <%next if i.name=="Brand" or i.name=="Product Name"%>
                  <%=i.value%>&nbsp;&nbsp;
             <%end%>
            <td>
          </tr>
        </tbody>
     </table>
     </div>
     <div style="Times New Roman&quot;;" class="table-responsive">          
      <table class="table">
        <tbody>
         <%@sku1.map do |i|%>
        <tr>
           <td><%=i.name %></td>
           <td><%=i.value%>
               <%=i.unit%></td>
       </tr>
     <%end%>
    </tbody>
 </table>
</div>
</p>
</div>

  
<div id="menu2" class="tab-pane fade">

  <p>
  
    <div class="pname">
  
     <b><%=@sku3.where(:name=>"Product Name").pluck(:value)[0]%></b>
  
    </div>

    <div style="Times New Roman&quot;;" class="table- responsive ">                
  
     <table  class="table">
  
       <tbody>

          <tr>

            <td>
           
              <%@sku3.map do |i|%>
             
                <%next if i.name=="Brand" or i.name=="Product Name"%>
             
                  <%=i.value%>&nbsp;&nbsp;
             <%end%>

            <td>

         </tr>

        </tbody>
        
     </table>
     
    </div>
      
    <div style="Times New Roman&quot;;" class="table-responsive">  
  
      <table class="table">
    <tbody>
     <%@sku6.map do |i|%>

     <tr>
     <td><%=link_to i.value,i.value,:target=>'_blank' %></a></td>
     </tr>
    <%end%>
     </tbody>
  </table>
  </div>
 
</div>
</div>

</div>
</div>
</div>
</div>
</div>
 </body>
</html>


<script>
$(document).ready(function(){
    $(".nav-tabs a").click(function(){
        $(this).tab('show');
    });
});
</script>


<script>
$(document).ready(function(){
    $('#content').hover(function() {
        $("#content").addClass('transition');
    
    }, function() {
        $("#content").removeClass('transition');
    });
});

</script>

app/views/products/result.html.erb
<html>

<head>

  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">


</head>

<body>



  <div class="body-wrap">

<div class="body-container">

<div class="body-header">

 You searched for "<%= $param2 %>"

</div>


<div class="body-content">

<div class="container">

<div class="row">

<div class="col-md-12">

   <ol class="breadcrumb">

  <%= page_entries_info $ssk%> 

  </ol>
</div>
</div>



  <center><%= will_paginate $ssk %></center>
  

  <% if $ssk.blank? %>

 <h4><font color="crimson">Oops! Your search didn't produce any result</font></h4>

<%else%>

<div class="row">
<div class="col-md-12">
<div class="compare-table">
<table class="table">
 
  
  <thead>

   <tr>

     <th>Image</th>

     <th>Item ID</th>

     <th>Product Name</th>

     <th>Manufactures</th>
     
      </tr>
    
 </thead>

 <%$ssk.each do|i|%>

 <%@p=Sku.where(:i_id=>i)%>

 <%@im=@p.where(:c_name=> "IMAGE").pluck(:value)[0]%>

 <tbody><tr class="odd">

 <%if @im.blank?%>

 <td><img src="/assets/not.jpeg" alt="Image not available"></td>

 <%else%>

 <td><%=image_tag @im, :height=>"100px", :width=>"100%" %></td>

 <%end%>
  <td><%=link_to i,  products_search_edit_path(i)%></td>

  <td><%=@p.where(:name=> "Product Name").pluck(:value)[0]%></td>

  <td><%=@p.where(:name=> "Manufacturer Name").pluck(:value)[0]%></td>

 </tr>
 
 <%end%></tbody><%end%>

 </table>
</div>
</div>
</div>

</div>
</div>
</div>
 </div>
 <center><%= will_paginate $ssk %></center>
 
 </body>
 
 </html>